<?php

declare(strict_types=1);

/*
 * Draggo
 *
 * Package: vtinnovations/draggo
 * Copyright: V&T Innovations Team
 * Licence: LGPL-3.0-or-later
 * Website: https://v-t.one
 */

namespace Vtinnovations\Draggo\Editor;

/**
 * Curated, type-aware map of inline-editable tl_content fields. A whitelist —
 * only these can be read/written through the inline editor.
 *
 * Widgets understood by the editor JS:
 *   headline  — value + unit (h1…h6, div)
 *   rte       — rich-text (HTML, inline toolbar)
 *   text      — single-line input
 *   code      — raw HTML/source textarea
 *   file      — single image path (files/…), picker datalist
 *   files     — multiple files/ paths (one per line) → serialized UUID array
 *   imgsize   — width / height / crop-mode
 *   select    — dropdown (choices in OPTIONS)
 *   bool      — checkbox (stored '1'/'')
 *   lines     — textarea, one item per line → serialized string array
 *   table     — 2-D cell grid → serialized rows
 *   pairs     — term/description rows → serialized [{key,value}]
 */
final class FieldRegistry
{
    /** @var array<string, list<string>> */
    public const MAP = [
        'text'             => ['headline', 'text'],
        'headline'         => ['headline'],
        'html'             => ['html'],
        'code'             => ['headline', 'code'],
        'markdown'         => ['code'],
        'unfiltered_html'  => ['html'],
        'hyperlink'        => ['linkTitle', 'url'],
        'image'            => ['singleSRC', 'size', 'alt'],
        'list'             => ['listtype', 'listitems'],
        'table'            => ['tableitems', 'summary', 'thead', 'tfoot', 'tleft', 'sortable'],
        'description_list' => ['descriptionList'],
        'download'         => ['singleSRC', 'linkTitle', 'titleText'],
        'downloads'        => ['multiSRC', 'sortBy'],
        'youtube'          => ['youtube', 'caption'],
        'vimeo'            => ['vimeo', 'caption'],
        'player'           => ['playerSRC', 'caption'],
        'module'           => ['module'],
        'form'             => ['form'],
        'draggo_form'      => ['draggo_form_id'],
        'gallery'          => ['multiSRC'],
        'article'          => ['articleAlias'],
        'teaser'           => ['article'],
        'draggo_nav'      => ['draggo_nav_root', 'draggo_nav_levels', 'draggo_nav_preset'],
        'draggo_inserttag' => ['draggo_it'],
        'draggo_icon'     => ['draggo_icon', 'draggo_icon_link'],
        'draggo_button'   => ['draggo_btn_text', 'draggo_btn_url', 'draggo_btn_blank', 'draggo_btn_icon', 'draggo_btn_icon_pos'],
        'draggo_spacer'   => ['draggo_space'],
        'draggo_divider'  => ['draggo_div_style', 'draggo_div_thickness', 'draggo_div_width', 'draggo_div_color', 'draggo_div_align', 'draggo_div_text'],
        'draggo_iconbox'  => ['draggo_ib_icon', 'draggo_ib_src', 'draggo_ib_alt', 'draggo_ib_title', 'draggo_ib_text', 'draggo_ib_pos'],
        'draggo_imagebox' => ['draggo_ib_src', 'draggo_ib_alt', 'draggo_ib_title', 'draggo_ib_text', 'draggo_ib_pos'],
        'draggo_accordion' => ['draggo_acc_multi', 'draggo_items'],
        'draggo_tabs'     => ['draggo_items'],
        'draggo_carousel' => ['draggo_car_src', 'draggo_car_per', 'draggo_car_fade', 'draggo_car_arrows', 'draggo_car_dots', 'draggo_car_auto', 'draggo_car_pause', 'draggo_car_speed'],
        'draggo_loop'     => ['draggo_loop_source', 'draggo_loop_parent', 'draggo_loop_archive', 'draggo_loop_calendar', 'draggo_loop_category', 'draggo_loop_featured', 'draggo_loop_order', 'draggo_loop_cols', 'draggo_loop_limit', 'draggo_loop_teaser', 'draggo_loop_more'],
        'draggo_alert'    => ['draggo_alert_type', 'draggo_alert_title', 'draggo_alert_text', 'draggo_alert_dismiss'],
        'draggo_quote'    => ['draggo_quote_text', 'draggo_quote_author'],
        'draggo_counter'  => ['draggo_counter_start', 'draggo_counter_end', 'draggo_counter_prefix', 'draggo_counter_suffix', 'draggo_counter_duration'],
        'draggo_progress' => ['draggo_progress_label', 'draggo_progress_value', 'draggo_progress_show'],
        'draggo_iconlist' => ['draggo_il_icon', 'draggo_il_items'],
        'draggo_cta'      => ['draggo_cta_title', 'draggo_cta_text', 'draggo_cta_btn', 'draggo_cta_url', 'draggo_cta_blank'],
        'draggo_social'   => ['draggo_social_items'],
        'draggo_flipbox'  => ['draggo_flip_icon', 'draggo_flip_ftitle', 'draggo_flip_ftext', 'draggo_flip_btitle', 'draggo_flip_btext', 'draggo_flip_btn', 'draggo_flip_url', 'draggo_flip_height'],
        'draggo_logo'     => ['draggo_logo_src', 'draggo_logo_alt', 'draggo_logo_link', 'draggo_logo_url'],
        'draggo_pagetitle' => ['draggo_pt_tag', 'draggo_pt_source'],
        'draggo_breadcrumb' => ['draggo_bc_sep'],
        'draggo_sitemap'  => ['draggo_sm_root', 'draggo_sm_levels'],
        'draggo_readerfield' => ['draggo_rf_source', 'draggo_rf_field', 'draggo_rf_tag'],
        'draggo_global'   => ['draggo_global_unit'],
        'draggo_countdown' => ['draggo_cd_date', 'draggo_cd_expired'],
        'draggo_opennow'  => ['draggo_on_hours', 'draggo_on_tz', 'draggo_on_open', 'draggo_on_closed', 'draggo_on_hidenext', 'draggo_on_noschema'],
        'draggo_map'      => ['draggo_map_query', 'draggo_map_zoom', 'draggo_map_height', 'draggo_map_consent'],
        'draggo_share'    => ['draggo_sh_facebook', 'draggo_sh_linkedin', 'draggo_sh_email', 'draggo_sh_copy'],
        'draggo_toc'      => ['draggo_toc_title', 'draggo_toc_levels'],
        'draggo_pricetable' => ['draggo_prt_title', 'draggo_prt_price', 'draggo_prt_period', 'draggo_prt_features', 'draggo_prt_btn', 'draggo_prt_url', 'draggo_prt_featured'],
        'draggo_pricelist' => ['draggo_prl_items'],
        'draggo_steps'    => ['draggo_stp_items'],
        'draggo_search'   => ['draggo_se_page', 'draggo_se_ph', 'draggo_se_btn'],
        'draggo_anim'     => ['draggo_an_before', 'draggo_an_words', 'draggo_an_after', 'draggo_an_effect', 'draggo_an_tag'],
        'draggo_hotspot'  => ['draggo_hs_img', 'draggo_hs_points'],
        'draggo_codeblock' => ['draggo_code', 'draggo_code_lang', 'draggo_code_copy'],
        'draggo_videoplaylist' => ['draggo_vp_items', 'draggo_vp_ratio'],
        'draggo_gallery'  => ['draggo_ga_images', 'draggo_ga_layout', 'draggo_ga_cols', 'draggo_ga_gap', 'draggo_ga_ratio', 'draggo_ga_hover', 'draggo_ga_link'],
        // Tilt-3D cards: title + text + optional per-card background image.
        'draggo_scroll_tilt' => ['draggo_ti_cards', 'draggo_ti_cols'],
        'draggo_themetoggle' => ['draggo_tt_style', 'draggo_tt_label', 'draggo_tt_size'],
    ];

    /** @var array<string,string> */
    public const WIDGET = [
        'headline'        => 'headline',
        'text'            => 'rte',
        'html'            => 'code',
        'code'            => 'code',
        'linkTitle'       => 'text',
        'url'             => 'text',
        'singleSRC'       => 'file',
        'size'            => 'imgsize',
        'alt'             => 'text',
        'listtype'        => 'select',
        'listitems'       => 'lines',
        'tableitems'      => 'table',
        'summary'         => 'text',
        'thead'           => 'bool',
        'tfoot'           => 'bool',
        'tleft'           => 'bool',
        'sortable'        => 'bool',
        'descriptionList' => 'pairs',
        'titleText'       => 'text',
        'multiSRC'        => 'files',
        'sortBy'          => 'select',
        'youtube'         => 'text',
        'vimeo'           => 'text',
        'caption'         => 'text',
        'playerSRC'       => 'files',
        'module'          => 'select',
        'form'            => 'select',
        'draggo_form_id'  => 'select',
        'draggo_ti_cards' => 'cards',
        'draggo_ti_cols'  => 'text',
        'draggo_tt_style' => 'select',
        'draggo_tt_label' => 'text',
        'draggo_tt_size'  => 'select',
        'articleAlias'    => 'select',
        'article'         => 'select',
        'draggo_nav_root'    => 'select',
        'draggo_nav_levels'  => 'select',
        'draggo_nav_preset'  => 'select',
        'draggo_it'          => 'text',
        'draggo_icon'        => 'icon',
        'draggo_icon_link'   => 'text',
        'draggo_btn_text'    => 'text',
        'draggo_btn_url'     => 'text',
        'draggo_btn_blank'   => 'bool',
        'draggo_btn_icon'    => 'icon',
        'draggo_btn_icon_pos' => 'select',
        'draggo_space'       => 'text',
        'draggo_div_style'   => 'select',
        'draggo_div_thickness' => 'text',
        'draggo_div_width'   => 'text',
        'draggo_div_color'   => 'color',
        'draggo_div_align'   => 'select',
        'draggo_div_text'    => 'text',
        'draggo_ib_icon'     => 'icon',
        'draggo_ib_src'      => 'file',
        'draggo_ib_alt'      => 'text',
        'draggo_ib_title'    => 'text',
        'draggo_ib_text'     => 'rte',
        'draggo_ib_pos'      => 'select',
        'draggo_items'       => 'accitems',
        'draggo_acc_multi'   => 'bool',
        'draggo_car_src'     => 'files',
        'draggo_car_per'     => 'text',
        'draggo_car_fade'    => 'bool',
        'draggo_car_arrows'  => 'bool',
        'draggo_car_dots'    => 'bool',
        'draggo_car_auto'    => 'bool',
        'draggo_car_pause'   => 'bool',
        'draggo_car_speed'   => 'text',
        'draggo_loop_source' => 'select',
        'draggo_loop_archive' => 'select',
        'draggo_loop_calendar' => 'select',
        'draggo_loop_category' => 'select',
        'draggo_loop_featured' => 'bool',
        'draggo_loop_order'  => 'select',
        'draggo_loop_parent' => 'select',
        'draggo_loop_cols'   => 'text',
        'draggo_loop_limit'  => 'text',
        'draggo_loop_teaser' => 'bool',
        'draggo_loop_more'   => 'bool',
        'draggo_alert_type'  => 'select',
        'draggo_alert_title' => 'text',
        'draggo_alert_text'  => 'rte',
        'draggo_alert_dismiss' => 'bool',
        'draggo_quote_text'  => 'rte',
        'draggo_quote_author' => 'text',
        'draggo_counter_start' => 'text',
        'draggo_counter_end' => 'text',
        'draggo_counter_prefix' => 'text',
        'draggo_counter_suffix' => 'text',
        'draggo_counter_duration' => 'text',
        'draggo_progress_label' => 'text',
        'draggo_progress_value' => 'text',
        'draggo_progress_show' => 'bool',
        'draggo_il_icon'     => 'icon',
        'draggo_il_items'    => 'lines',
        'draggo_cta_title'   => 'text',
        'draggo_cta_text'    => 'rte',
        'draggo_cta_btn'     => 'text',
        'draggo_cta_url'     => 'text',
        'draggo_cta_blank'   => 'bool',
        'draggo_social_items' => 'iconpairs',
        'draggo_flip_icon'   => 'icon',
        'draggo_flip_ftitle' => 'text',
        'draggo_flip_ftext'  => 'rte',
        'draggo_flip_btitle' => 'text',
        'draggo_flip_btext'  => 'rte',
        'draggo_flip_btn'    => 'text',
        'draggo_flip_url'    => 'text',
        'draggo_flip_height' => 'text',
        'draggo_logo_src'    => 'file',
        'draggo_logo_alt'    => 'text',
        'draggo_logo_link'   => 'select',
        'draggo_logo_url'    => 'text',
        'draggo_pt_tag'      => 'select',
        'draggo_pt_source'   => 'select',
        'draggo_bc_sep'      => 'text',
        'draggo_sm_root'     => 'select',
        'draggo_sm_levels'   => 'text',
        'draggo_rf_source'   => 'select',
        'draggo_rf_field'    => 'select',
        'draggo_rf_tag'      => 'select',
        'draggo_global_unit' => 'select',
        'draggo_cd_date'     => 'datetime',
        'draggo_cd_expired'  => 'text',
        'draggo_on_hours'    => 'hours',
        'draggo_on_tz'       => 'select',
        'draggo_on_open'     => 'text',
        'draggo_on_closed'   => 'text',
        'draggo_on_hidenext' => 'bool',
        'draggo_on_noschema' => 'bool',
        'draggo_map_query'   => 'text',
        'draggo_map_zoom'    => 'text',
        'draggo_map_height'  => 'text',
        'draggo_map_consent' => 'bool',
        'draggo_sh_facebook' => 'bool',
        'draggo_sh_linkedin' => 'bool',
        'draggo_sh_email'    => 'bool',
        'draggo_sh_copy'     => 'bool',
        'draggo_toc_title'   => 'text',
        'draggo_toc_levels'  => 'select',
        'draggo_prt_title'   => 'text',
        'draggo_prt_price'   => 'text',
        'draggo_prt_period'  => 'text',
        'draggo_prt_features' => 'lines',
        'draggo_prt_btn'     => 'text',
        'draggo_prt_url'     => 'text',
        'draggo_prt_featured' => 'bool',
        'draggo_prl_items'   => 'pairs',
        'draggo_stp_items'   => 'pairs',
        'draggo_se_page'     => 'select',
        'draggo_se_ph'       => 'text',
        'draggo_se_btn'      => 'text',
        'draggo_an_before'   => 'text',
        'draggo_an_words'    => 'lines',
        'draggo_an_after'    => 'text',
        'draggo_an_effect'   => 'select',
        'draggo_an_tag'      => 'select',
        'draggo_hs_img'      => 'file',
        'draggo_hs_points'   => 'pairs',
        'draggo_code'        => 'code',
        'draggo_code_lang'   => 'text',
        'draggo_code_copy'   => 'bool',
        'draggo_vp_items'    => 'pairs',
        'draggo_vp_ratio'    => 'select',
        'draggo_ga_images'   => 'files',
        'draggo_ga_layout'   => 'select',
        'draggo_ga_cols'     => 'text',
        'draggo_ga_gap'      => 'text',
        'draggo_ga_ratio'    => 'select',
        'draggo_ga_hover'    => 'select',
        'draggo_ga_link'     => 'select',
    ];

    /** @var array<string,string> */
    public const LABEL = [
        'headline'        => 'Überschrift',
        'text'            => 'Text',
        'html'            => 'HTML',
        'code'            => 'Quelltext',
        'linkTitle'       => 'Linktext',
        'url'             => 'URL',
        'singleSRC'       => 'Bild',
        'size'            => 'Bildgröße',
        'alt'             => 'Alt-Text',
        'listtype'        => 'Listentyp',
        'listitems'       => 'Einträge (eine pro Zeile)',
        'tableitems'      => 'Tabelle',
        'summary'         => 'Zusammenfassung',
        'thead'           => 'Kopfzeile',
        'tfoot'           => 'Fußzeile',
        'tleft'           => 'Erste Spalte als Kopf',
        'sortable'        => 'Sortierbar',
        'descriptionList' => 'Begriffe & Beschreibungen',
        'titleText'       => 'Titel',
        'multiSRC'        => 'Dateien (ein Pfad pro Zeile)',
        'sortBy'          => 'Sortierung',
        'youtube'         => 'YouTube-ID/URL',
        'vimeo'           => 'Vimeo-ID/URL',
        'caption'         => 'Bildunterschrift',
        'playerSRC'       => 'Mediendateien (ein Pfad pro Zeile)',
        'module'          => 'Modul',
        'form'            => 'Formular',
        'draggo_form_id'  => 'Formular',
        'draggo_ti_cards' => 'Karten (Titel · Text · Hintergrundbild)',
        'draggo_ti_cols'  => 'Spalten (1–6)',
        'draggo_tt_style' => 'Stil',
        'draggo_tt_label' => 'Beschriftung (bei „Icon + Text")',
        'draggo_tt_size'  => 'Größe',
        'articleAlias'    => 'Artikel',
        'article'         => 'Artikel',
        'draggo_nav_root'    => 'Start-Seite',
        'draggo_nav_levels'  => 'Ebenen',
        'draggo_nav_preset'  => 'Design',
        'draggo_it'          => 'Insert-Tag (z. B. date oder news_url::3)',
        'draggo_icon'        => 'Icon',
        'draggo_icon_link'   => 'Link (optional)',
        'draggo_btn_text'    => 'Button-Text',
        'draggo_btn_url'     => 'Link (URL oder {{link_url::id}})',
        'draggo_btn_blank'   => 'In neuem Fenster öffnen',
        'draggo_btn_icon'    => 'Icon',
        'draggo_btn_icon_pos' => 'Icon-Position',
        'draggo_space'       => 'Höhe (px)',
        'draggo_div_style'   => 'Linien-Stil',
        'draggo_div_thickness' => 'Dicke (px)',
        'draggo_div_width'   => 'Breite (%)',
        'draggo_div_color'   => 'Farbe',
        'draggo_div_align'   => 'Ausrichtung',
        'draggo_div_text'    => 'Text in der Mitte (optional)',
        'draggo_ib_icon'     => 'Icon (statt Bild)',
        'draggo_ib_src'      => 'Icon / Bild',
        'draggo_ib_alt'      => 'Alt-Text (Bild)',
        'draggo_ib_title'    => 'Titel',
        'draggo_ib_text'     => 'Text',
        'draggo_ib_pos'      => 'Medien-Position',
        'draggo_items'       => 'Einträge (Titel / Inhalt)',
        'draggo_acc_multi'   => 'Mehrere gleichzeitig offen',
        'draggo_car_src'     => 'Bilder',
        'draggo_car_per'     => 'Sichtbare Folien',
        'draggo_car_fade'    => 'Überblenden (Fade)',
        'draggo_car_arrows'  => 'Pfeile',
        'draggo_car_dots'    => 'Punkte',
        'draggo_car_auto'    => 'Autoplay',
        'draggo_car_pause'   => 'Pause bei Hover',
        'draggo_car_speed'   => 'Autoplay-Intervall (Sek.)',
        'draggo_loop_source' => 'Quelle',
        'draggo_loop_archive' => 'News-Archiv',
        'draggo_loop_calendar' => 'Kalender',
        'draggo_loop_category' => 'News-Kategorie (optional)',
        'draggo_loop_featured' => 'Nur hervorgehobene',
        'draggo_loop_order'  => 'Sortierung',
        'draggo_loop_parent' => 'Start-Seite (Unterseiten anzeigen)',
        'draggo_loop_cols'   => 'Spalten (1–4)',
        'draggo_loop_limit'  => 'Anzahl (0 = alle)',
        'draggo_loop_teaser' => 'Beschreibung zeigen',
        'draggo_loop_more'   => 'Mehr-Link zeigen',
        'draggo_alert_type'  => 'Typ',
        'draggo_alert_title' => 'Titel',
        'draggo_alert_text'  => 'Text',
        'draggo_alert_dismiss' => 'Schließbar',
        'draggo_quote_text'  => 'Zitat',
        'draggo_quote_author' => 'Autor / Quelle',
        'draggo_counter_start' => 'Startwert',
        'draggo_counter_end' => 'Zielwert',
        'draggo_counter_prefix' => 'Präfix (z. B. +)',
        'draggo_counter_suffix' => 'Suffix (z. B. %)',
        'draggo_counter_duration' => 'Dauer (ms)',
        'draggo_progress_label' => 'Beschriftung',
        'draggo_progress_value' => 'Wert (0–100)',
        'draggo_progress_show' => 'Prozent anzeigen',
        'draggo_il_icon'     => 'Icon (für alle Punkte)',
        'draggo_il_items'    => 'Punkte (einer pro Zeile)',
        'draggo_cta_title'   => 'Titel',
        'draggo_cta_text'    => 'Text',
        'draggo_cta_btn'     => 'Button-Text',
        'draggo_cta_url'     => 'Button-Link',
        'draggo_cta_blank'   => 'In neuem Fenster öffnen',
        'draggo_social_items' => 'Netzwerke (Icon wählen + URL)',
        'draggo_flip_icon'   => 'Icon (Vorderseite)',
        'draggo_flip_ftitle' => 'Titel (Vorderseite)',
        'draggo_flip_ftext'  => 'Text (Vorderseite)',
        'draggo_flip_btitle' => 'Titel (Rückseite)',
        'draggo_flip_btext'  => 'Text (Rückseite)',
        'draggo_flip_btn'    => 'Button-Text (Rückseite)',
        'draggo_flip_url'    => 'Button-Link (Rückseite)',
        'draggo_flip_height' => 'Höhe (px)',
        'draggo_logo_src'    => 'Logo-Bild',
        'draggo_logo_alt'    => 'Alternativtext',
        'draggo_logo_link'   => 'Verlinkung',
        'draggo_logo_url'    => 'Eigene URL',
        'draggo_pt_tag'      => 'HTML-Tag',
        'draggo_pt_source'   => 'Quelle',
        'draggo_bc_sep'      => 'Trennzeichen',
        'draggo_sm_root'     => 'Start-Seite (leer = aktuelle Website)',
        'draggo_sm_levels'   => 'Ebenen (1–6)',
        'draggo_rf_source'   => 'Datenquelle',
        'draggo_rf_field'    => 'Feld',
        'draggo_rf_tag'      => 'HTML-Tag (bei Titel)',
        'draggo_global_unit' => 'Einheit (Block)',
        'draggo_cd_date'     => 'Zieldatum',
        'draggo_cd_expired'  => 'Text nach Ablauf',
        'draggo_on_hours'    => 'Öffnungszeiten',
        'draggo_on_tz'       => 'Zeitzone',
        'draggo_on_open'     => 'Text „geöffnet"',
        'draggo_on_closed'   => 'Text „geschlossen"',
        'draggo_on_hidenext' => 'Schließt-/Öffnet-Zeit ausblenden',
        'draggo_on_noschema' => 'schema.org-Daten ausblenden',
        'draggo_map_query'   => 'Adresse / Ort',
        'draggo_map_zoom'    => 'Zoom (1–21)',
        'draggo_map_height'  => 'Höhe (px)',
        'draggo_map_consent' => 'DSGVO: erst nach Klick laden',
        'draggo_sh_facebook' => 'Facebook',
        'draggo_sh_linkedin' => 'LinkedIn',
        'draggo_sh_email'    => 'E-Mail',
        'draggo_sh_copy'     => 'Link kopieren',
        'draggo_toc_title'   => 'Überschrift',
        'draggo_toc_levels'  => 'Ebenen',
        'draggo_prt_title'   => 'Titel (z. B. Basis)',
        'draggo_prt_price'   => 'Preis (z. B. 29 €)',
        'draggo_prt_period'  => 'Zeitraum (z. B. /Monat)',
        'draggo_prt_features' => 'Leistungen (eine pro Zeile)',
        'draggo_prt_btn'     => 'Button-Text',
        'draggo_prt_url'     => 'Button-Link',
        'draggo_prt_featured' => 'Hervorheben',
        'draggo_prl_items'   => 'Einträge (Name / Preis)',
        'draggo_stp_items'   => 'Schritte (Titel / Text)',
        'draggo_se_page'     => 'Ergebnis-Seite',
        'draggo_se_ph'       => 'Platzhalter',
        'draggo_se_btn'      => 'Button-Text',
        'draggo_an_before'   => 'Text davor',
        'draggo_an_words'    => 'Rotierende Wörter (eines pro Zeile)',
        'draggo_an_after'    => 'Text danach',
        'draggo_an_effect'   => 'Effekt',
        'draggo_an_tag'      => 'HTML-Tag',
        'draggo_hs_img'      => 'Bild',
        'draggo_hs_points'   => 'Punkte (x,y / Text)',
        'draggo_code'        => 'Code',
        'draggo_code_lang'   => 'Sprache (Label)',
        'draggo_code_copy'   => 'Kopier-Button',
        'draggo_vp_items'    => 'Videos (Titel / URL)',
        'draggo_vp_ratio'    => 'Seitenverhältnis',
        'draggo_ga_images'   => 'Bilder',
        'draggo_ga_layout'   => 'Layout',
        'draggo_ga_cols'     => 'Spalten (1–8)',
        'draggo_ga_gap'      => 'Abstand (px)',
        'draggo_ga_ratio'    => 'Kachel-Format (nur Kacheln)',
        'draggo_ga_hover'    => 'Hover-Effekt',
        'draggo_ga_link'     => 'Verlinkung',
    ];

    /**
     * Choice lists for `select` widgets. First column = stored value.
     *
     * @var array<string, list<array{0:string,1:string}>>
     */
    public const OPTIONS = [
        'listtype' => [
            ['unordered', 'Aufzählung (•)'],
            ['ordered', 'Nummeriert (1.)'],
        ],
        'sortBy' => [
            ['', '—'],
            ['name_asc', 'Name A→Z'],
            ['name_desc', 'Name Z→A'],
            ['date_asc', 'Datum ↑'],
            ['date_desc', 'Datum ↓'],
            ['meta', 'Meta-Reihenfolge'],
            ['random', 'Zufällig'],
        ],
        'draggo_nav_levels' => [['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5']],
        'draggo_nav_preset' => [['horizontal', 'Horizontal'], ['vertical', 'Seiten-Navi'], ['hamburger', 'Hamburger']],
        'draggo_div_style'  => [['solid', 'Durchgezogen'], ['dashed', 'Gestrichelt'], ['dotted', 'Gepunktet'], ['double', 'Doppelt']],
        'draggo_div_align'  => [['left', 'Links'], ['center', 'Mitte'], ['right', 'Rechts']],
        'draggo_tt_style'   => [['icon', 'Nur Icon (Sonne/Mond)'], ['text', 'Icon + Text'], ['switch', 'Schiebeschalter']],
        'draggo_tt_size'    => [['sm', 'Klein'], ['md', 'Mittel'], ['lg', 'Groß']],
        'draggo_btn_icon_pos' => [['before', 'Vor dem Text'], ['after', 'Nach dem Text']],
        'draggo_ib_pos'     => [['top', 'Oben'], ['left', 'Links'], ['right', 'Rechts']],
        'draggo_loop_source' => [['pages', 'Seiten (Unterseiten)'], ['news', 'News-Archiv'], ['events', 'Termine (Kalender)']],
        'draggo_loop_order'  => [['default', 'Standard (neueste / Reihenfolge)'], ['oldest', 'Älteste zuerst'], ['alpha', 'Alphabetisch']],
        'draggo_alert_type'  => [['info', 'Info (blau)'], ['success', 'Erfolg (grün)'], ['warning', 'Warnung (gelb)'], ['error', 'Fehler (rot)']],
        'draggo_logo_link'   => [['home', 'Startseite'], ['custom', 'Eigene URL'], ['none', 'Kein Link']],
        'draggo_pt_tag'      => [['h1', 'H1'], ['h2', 'H2'], ['h3', 'H3'], ['div', 'Div']],
        'draggo_pt_source'   => [['title', 'Seitentitel'], ['pageTitle', 'Navigationstitel'], ['description', 'Beschreibung']],
        'draggo_toc_levels'  => [['2', 'H2'], ['2-3', 'H2–H3'], ['2-4', 'H2–H4']],
        'draggo_an_effect'   => [['rotate', 'Rotieren'], ['type', 'Tippen']],
        'draggo_an_tag'      => [['h1', 'H1'], ['h2', 'H2'], ['h3', 'H3'], ['div', 'Div']],
        'draggo_vp_ratio'    => [['16:9', '16:9'], ['4:3', '4:3'], ['1:1', '1:1']],
        'draggo_ga_layout'   => [['grid', 'Raster (Grid)'], ['masonry', 'Masonry'], ['tiles', 'Kacheln (gleich groß)']],
        'draggo_ga_ratio'    => [['1:1', '1:1 Quadrat'], ['4:3', '4:3'], ['3:4', '3:4 Hoch'], ['16:9', '16:9'], ['3:2', '3:2']],
        'draggo_ga_hover'    => [['none', 'Keiner'], ['zoom', 'Zoom'], ['overlay', 'Verdunkeln'], ['grayscale', 'Graustufen→Farbe']],
        'draggo_ga_link'     => [['none', 'Keine'], ['file', 'Bild öffnen'], ['lightbox', 'Lightbox']],
        'draggo_rf_source'   => [['auto', 'Automatisch (News/Event)'], ['news', 'Nur News'], ['event', 'Nur Termine']],
        'draggo_rf_field'    => [['title', 'Titel'], ['teaser', 'Teaser'], ['image', 'Aufmacherbild'], ['date', 'Datum'], ['author', 'Autor']],
        'draggo_rf_tag'      => [['h1', 'H1'], ['h2', 'H2'], ['h3', 'H3'], ['div', 'Div']],
        'draggo_on_tz'       => [
            ['Europe/Berlin', 'Berlin / Deutschland'], ['Europe/Vienna', 'Wien / Österreich'], ['Europe/Zurich', 'Zürich / Schweiz'],
            ['Europe/London', 'London'], ['Europe/Paris', 'Paris'], ['Europe/Madrid', 'Madrid'], ['Europe/Rome', 'Rom'],
            ['Europe/Amsterdam', 'Amsterdam'], ['Europe/Warsaw', 'Warschau'], ['Europe/Athens', 'Athen'], ['Europe/Istanbul', 'Istanbul'], ['Europe/Moscow', 'Moskau'],
            ['America/New_York', 'New York'], ['America/Chicago', 'Chicago'], ['America/Denver', 'Denver'], ['America/Los_Angeles', 'Los Angeles'], ['America/Sao_Paulo', 'São Paulo'],
            ['Asia/Dubai', 'Dubai'], ['Asia/Kolkata', 'Indien'], ['Asia/Singapore', 'Singapur'], ['Asia/Tokyo', 'Tokio'], ['Australia/Sydney', 'Sydney'], ['UTC', 'UTC'],
        ],
    ];

    /**
     * Fields that MUST be filled before an element can be saved — guarantees
     * every Draggo element actually has content. ALL listed fields are
     * required (most types list one). Types not listed have no requirement.
     *
     * @var array<string, list<string>>
     */
    public const REQUIRED = [
        'text'             => ['text'],
        'headline'         => ['headline'],
        'html'             => ['html'],
        'code'             => ['code'],
        'markdown'         => ['code'],
        'unfiltered_html'  => ['html'],
        'hyperlink'        => ['url'],
        'image'            => ['singleSRC'],
        'list'             => ['listitems'],
        'table'            => ['tableitems'],
        'description_list' => ['descriptionList'],
        'download'         => ['singleSRC'],
        'downloads'        => ['multiSRC'],
        'youtube'          => ['youtube'],
        'vimeo'            => ['vimeo'],
        'player'           => ['playerSRC'],
        'module'           => ['module'],
        'form'             => ['form'],
        'gallery'          => ['multiSRC'],
        'article'          => ['articleAlias'],
        'teaser'           => ['article'],
        'draggo_inserttag' => ['draggo_it'],
        'draggo_icon'     => ['draggo_icon'],
        'draggo_button'   => ['draggo_btn_text'],
        'draggo_iconbox'  => ['draggo_ib_title'],
        'draggo_imagebox' => ['draggo_ib_title'],
        'draggo_accordion' => ['draggo_items'],
        'draggo_tabs'     => ['draggo_items'],
        'draggo_carousel' => ['draggo_car_src'],
        'draggo_quote'    => ['draggo_quote_text'],
        'draggo_counter'  => ['draggo_counter_end'],
        'draggo_progress' => ['draggo_progress_value'],
        'draggo_iconlist' => ['draggo_il_items'],
        'draggo_social'   => ['draggo_social_items'],
        'draggo_logo'     => ['draggo_logo_src'],
        'draggo_global'   => ['draggo_global_unit'],
        'draggo_countdown' => ['draggo_cd_date'],
        'draggo_map'      => ['draggo_map_query'],
        'draggo_pricetable' => ['draggo_prt_title'],
        'draggo_pricelist' => ['draggo_prl_items'],
        'draggo_steps'    => ['draggo_stp_items'],
        'draggo_search'   => ['draggo_se_page'],
        'draggo_anim'     => ['draggo_an_words'],
        'draggo_hotspot'  => ['draggo_hs_img'],
        'draggo_codeblock' => ['draggo_code'],
        'draggo_videoplaylist' => ['draggo_vp_items'],
        'draggo_gallery'  => ['draggo_ga_images'],
    ];

    /** Headline tag options. */
    public const HEADLINE_UNITS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'div'];

    /**
     * @return list<string>
     */
    public static function fieldsFor(string $type): array
    {
        return self::MAP[$type] ?? [];
    }
}
